"""The data-quality report: checks, partial days and the reconciliation, as JSON and Markdown."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from drivecast.quality import checks, published

TOTALS = ("rows", "drives", "failures")


def build(con: Any, files: list[str], work: Path) -> dict[str, Any]:
    """Checks and reconciliation; ``files`` are the bronze months behind the view "bronze"."""
    results = checks.run(con, files, work)
    (drives,) = con.execute("SELECT count(*) FROM spans").fetchone()
    return {
        "drives": int(drives),
        "checks": results,
        "partial_days": checks.partial_day_ranges(con),
        "reconciliation": published.reconcile(con),
    }


def _n(value: float | None) -> str:
    if value is None:
        return "-"
    return f"{value:,.2f}" if isinstance(value, float) else f"{value:,}"


def _diff(pub: float | None, ours: float) -> str:
    if pub is None:
        return ""
    if isinstance(pub, float):
        return f"{ours - pub:+.2f}"
    return f"{ours - pub:+,} ({100 * (ours - pub) / pub:+.2f}%)" if pub else ""


def markdown(report: dict[str, Any]) -> str:
    c = report["checks"]
    years = sorted(c["rows"]["by_year"])
    lines = [
        "# Data quality",
        "",
        "Generated by `drivecast quality` from the bronze lake. Every check counts what it",
        "affects; nothing is changed in bronze. The silver layer applies the rules listed at the",
        "end.",
        "",
        "## The lake",
        "",
        "| year | rows | drives | failures |",
        "|---|---:|---:|---:|",
    ]
    for y in years:
        lines.append(f"| {y} | " + " | ".join(_n(c[t]["by_year"].get(y, 0)) for t in TOTALS) + " |")
    lines.append(
        f"| **all** | {_n(c['rows']['total'])} | {_n(report['drives'])} | "
        f"{_n(c['failures']['total'])} |"
    )
    lines += ["", "## Checks", "", "| check | affected | unit | by year |", "|---|---:|---|---|"]
    for name, r in c.items():
        if name in TOTALS:
            continue
        years_text = ", ".join(f"{y}: {_n(v)}" for y, v in r["by_year"].items())
        lines.append(f"| {r['description']} | {_n(r['total'])} | {r['unit']} | {years_text} |")
    lines += ["", "## Partial days", ""]
    if report["partial_days"]:
        lines += [
            "| from | to | days | fewest reports | drives alive |",
            "|---|---|---:|---:|---:|",
        ]
        lines += [
            f"| {p['from']} | {p['to']} | {p['days']} | {_n(p['min_reports'])} | {_n(p['alive'])} |"
            for p in report["partial_days"]
        ]
    else:
        lines.append("None.")
    lines += [
        "",
        "## Reconciliation with the published numbers",
        "",
        "Each quarter uses the inclusion rule Backblaze stated for it. Drives in certification",
        "testing are removed by Backblaze but not marked in the data.",
        "",
        "| quarter | quantity | published | lake | difference |",
        "|---|---|---:|---:|---:|",
    ]
    for r in report["reconciliation"]:
        for field, pub in r["published"].items():
            ours = r["lake"][field]
            lines.append(
                f"| [{r['quarter']}]({r['source']}) | {field.replace('_', ' ')} | {_n(pub)} | "
                f"{_n(ours)} | {_diff(pub, ours)} |"
            )
    notes = [f"- {r['quarter']}: {r['note']}" for r in report["reconciliation"] if r.get("note")]
    if notes:
        lines += ["", *notes]
    return "\n".join(lines) + "\n"
